formas:
 - nombre : "Dependencias"
   campos:
    - nombre: "dependenciaBaseDatos"
      etiqueta: "Dependencia base de datos, ej: mysql"
      descripcion: "Esta es la dependencia que se inyectara en el package.json"
    - nombre: "versionDependenciaBaseDatos"
      etiqueta: "Version de la dependencia de base de datos, ej: ^2.18.1"
      descripcion: "Esta es la dependencia que se inyectara en el package.json"
 - nombre : "Orm Config"
   campos:
    - nombre: "tipoBaseDatos"
      etiqueta: "Tipo de base de datos a usar, ej: mysql"
      descripcion: "Debe coincidir con la dependencia seleccionada ej: mysql"
    - nombre: "host"
      etiqueta: "Hos para establecer conexión, ej: localhost"
      descripcion: "ejm: localhost"
    - nombre: "puerto"
      etiqueta: "Puerta de conexión a la base de datos, ej: 3307"
      descripcion: "ej: 3307"
    - nombre: "username"
      etiqueta: "Usuario de base de datos"
      descripcion: "ej: root"
    - nombre: "password"
      etiqueta: "Password del usuario"
      descripcion: "ej: root"
    - nombre: "baseDatos"
      etiqueta: "Nombre de la base de datos. ej: test"
      descripcion: "ej: test"

